config/routes.rb
Rails.application.routes.draw do
  resources :orders

  resources :carts

  resources :lineitems

  get 'shop/index'

  resources :comments

  resources :tests

  resources :users

  resources :showings

  resources :tickets

	resources :movies do
		resources :comments
	end

	resources :carts do
		resources:lineitems
	end
	
	resources :theatres
	
	get '/search'  =>'showings#search'
	
	controller :sessions do
				get 'login'=>:new
				post 'login'=>:create
				get 'logout'=>:destroy
				delete 'logout'=>:destroy
	end

  root 'pages#homepage'

	
	
end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :lineitems
	
	def add_ticket(showing_id)
		current_item =lineitems.find_by_showing_id(showing_id)
		if current_item
			current_item.quantity+=1
		else
			current_item=lineitems.new(showing_id:showing_id)
			current_item.quantity=1
		end
		current_item
	end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to:user
	belongs_to:movie
end

app/models/lineitem.rb
class Lineitem < ActiveRecord::Base
	belongs_to :order
	belongs_to :cart
	belongs_to :showing
end

app/models/movie.rb
class Movie < ActiveRecord::Base
	has_many :showings, dependent: :destroy
		has_many :comments,:dependent=> :destroy

		validate :must_have_valid_trailer
	def must_have_valid_trailer 
	   unless trailer.include?("<iframe")   
		errors.add(:trailer, "Must include an iframe tag") 
	   end  
	end
	
	def average_stars
		comments.average(:stars)
	end

end

app/models/order.rb
class Order < ActiveRecord::Base
	has_many :lineitems
	belongs_to :user
	
	def add_lineitems_from_cart(cart)
		cart.lineitems.each do |item|
			item.cart_id=nil
			lineitems << item
		end
	end
end

app/models/showing.rb
class Showing < ActiveRecord::Base
	belongs_to :theatre
	belongs_to :movie
	has_many :lineitems

	validates :theatre_id, presence: true
	validates :movie_id, presence: true
	
	def self.search(query)
		find_by_sql ["SELECT s.* FROM showings s,movies m WHERE m.name LIKE ? AND s.movie_id=m.id;", "%#{query}%"]

	end


end

app/models/theatre.rb
class Theatre < ActiveRecord::Base
	has_many :showings
	
	geocoded_by :location
	after_validation :geocode, :if => :location_changed?

	
	validates :theatreName, presence: true
	validates :location, presence: true
	validates :capacity, presence: true

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
	belongs_to :user
	belongs_to :showing
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :tickets
	has_many :comments
	has_many :orders
	
	
	validates :username, format:{with:/\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/}
	has_secure_password
	validates :password_digest, presence: true
	
	
end

app/controllers/showings_controller.rb
class ShowingsController < ApplicationController
  before_action :set_showing, only: [:show, :edit, :update, :destroy]

  # GET /showings
  # GET /showings.json
  def index
    @showings = Showing.all
  end

  # GET /showings/1
  # GET /showings/1.json
  def show
  end
  
  def search
		@showings =Showing.search params[:query]
		unless @showings.empty?
				render 'index'
		else
						render 'index'

		end
	end

  # GET /showings/new
  def new
    @showing = Showing.new
  end

  # GET /showings/1/edit
  def edit
  end

  # POST /showings
  # POST /showings.json
  def create
    @showing = Showing.new(showing_params)

    respond_to do |format|
      if @showing.save
        format.html { redirect_to @showing, notice: 'Showing was successfully created.' }
        format.json { render :show, status: :created, location: @showing }
      else
        format.html { render :new }
        format.json { render json: @showing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /showings/1
  # PATCH/PUT /showings/1.json
  def update
    respond_to do |format|
      if @showing.update(showing_params)
        format.html { redirect_to @showing, notice: 'Showing was successfully updated.' }
        format.json { render :show, status: :ok, location: @showing }
      else
        format.html { render :edit }
        format.json { render json: @showing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /showings/1
  # DELETE /showings/1.json
  def destroy
    @showing.destroy
    respond_to do |format|
      format.html { redirect_to showings_url, notice: 'Showing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_showing
      @showing = Showing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def showing_params
      params.require(:showing).permit(:theatre_id, :movie_id, :dateAndTime)
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/lineitems_helper.rb
module LineitemsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/helpers/showings_helper.rb
module ShowingsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/theatres_helper.rb
module TheatresHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/showings/_form.html.erb
<%= form_for(@showing) do |f| %>
  <% if @showing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@showing.errors.count, "error") %> prohibited this showing from being saved:</h2>

      <ul>
      <% @showing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :theatre_id %><br>
    <%= f.collection_select:theatre_id, Theatre.all,:id ,:theatreName%>
  </div>
  
  <div class="field">
    <%= f.label :movie_id %><br>
    <%= f.collection_select:movie_id, Movie.all,:id ,:name%>
  </div>
  
  <div class="field">
    <%= f.label :Happening %><br>
    <%= f.datetime_local_field :dateAndTime%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/showings/_search.html.erb
<%=form_tag(search_path, :method=>"get") do%>
	<%=text_field_tag(:query,params[:query])%>
	<%=submit_tag "Search by movie name"%>
<%end%>

app/views/showings/edit.html.erb
<h1>Editing showing</h1>

<%= render 'form' %>

<%= link_to 'Show', @showing %> |
<%= link_to 'Back', showings_path %>

app/views/showings/index.html.erb
<h1>Listing showings</h1>
<div id="search">
	<%=render 'search'%>
</div>

<table class="table">
  <thead>
    <tr>
      <th>Theatre</th>
      <th>Movie</th>
      <th>Happening</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @showings.each do |showing| %>
      <tr>
        <td><%= showing.theatre.theatreName %></td>
        <td><%= showing.movie.name %></td>
        <td><%= showing.dateAndTime %></td>
		<td><%=button_to 'Buy Ticket',lineitems_path(showing_id:showing) %></td>
        <td><%= link_to 'Show', showing %></td>
        <td><%= link_to 'Edit', edit_showing_path(showing) %></td>
        <td><%= link_to 'Destroy', showing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Showing', new_showing_path %>

app/views/showings/new.html.erb
<h1>New showing</h1>

<%= render 'form' %>

<%= link_to 'Back', showings_path %>

app/views/showings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Theatre:</strong>
  <%= @showing.theatre.theatreName %>
</p>

<p>
  <strong>Movie:</strong>
  <%= @showing.movie.name %>
</p>

<p>
  <strong>Date and Time:</strong>
  <%= @showing.dateAndTime %>
</p>

<%= link_to 'Edit', edit_showing_path(@showing) %> |
<%= link_to 'Back', showings_path %>