config/routes.rb
Rails.application.routes.draw do
  resources :orders

  resources :carts

  resources :lineitems

  get 'shop/index'

  resources :comments

  resources :tests

  resources :users

  resources :showings

  resources :tickets

	resources :movies do
		resources :comments
	end

	resources :carts do
		resources:lineitems
	end
	
	resources :theatres
	
	get '/search'  =>'showings#search'
	
	controller :sessions do
				get 'login'=>:new
				post 'login'=>:create
				get 'logout'=>:destroy
				delete 'logout'=>:destroy
	end

  root 'pages#homepage'

	
	
end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :lineitems
	
	def add_ticket(showing_id)
		current_item =lineitems.find_by_showing_id(showing_id)
		if current_item
			current_item.quantity+=1
		else
			current_item=lineitems.new(showing_id:showing_id)
			current_item.quantity=1
		end
		current_item
	end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to:user
	belongs_to:movie
end

app/models/lineitem.rb
class Lineitem < ActiveRecord::Base
	belongs_to :order
	belongs_to :cart
	belongs_to :showing
end

app/models/movie.rb
class Movie < ActiveRecord::Base
	has_many :showings, dependent: :destroy
		has_many :comments,:dependent=> :destroy

		validate :must_have_valid_trailer
	def must_have_valid_trailer 
	   unless trailer.include?("<iframe")   
		errors.add(:trailer, "Must include an iframe tag") 
	   end  
	end
	
	def average_stars
		comments.average(:stars)
	end

end

app/models/order.rb
class Order < ActiveRecord::Base
	has_many :lineitems
	belongs_to :user
	
	def add_lineitems_from_cart(cart)
		cart.lineitems.each do |item|
			item.cart_id=nil
			lineitems << item
		end
	end
end

app/models/showing.rb
class Showing < ActiveRecord::Base
	belongs_to :theatre
	belongs_to :movie
	has_many :lineitems

	validates :theatre_id, presence: true
	validates :movie_id, presence: true
	
	def self.search(query)
		find_by_sql ["SELECT s.* FROM showings s,movies m WHERE m.name LIKE ? AND s.movie_id=m.id;", "%#{query}%"]

	end


end

app/models/theatre.rb
class Theatre < ActiveRecord::Base
	has_many :showings
	
	geocoded_by :location
	after_validation :geocode, :if => :location_changed?

	
	validates :theatreName, presence: true
	validates :location, presence: true
	validates :capacity, presence: true

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
	belongs_to :user
	belongs_to :showing
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :tickets
	has_many :comments
	has_many :orders
	
	
	validates :username, format:{with:/\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/}
	has_secure_password
	validates :password_digest, presence: true
	
	
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/helpers/showings_helper.rb
module ShowingsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/homepage.html.erb
<h1>hello<h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MovieApp</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
<div id="columns">
	<ul>
		<%if !signed_in?%>
			<li><%=link_to "Sign In",login_path %></li>
			<li><%=link_to "Register",new_user_path %></li>
		<%else%>
			<li> Signed In as: <%=@current_user.firstName%></li>
			<li><%=link_to "Sign Out",logout_path %></li>
		<%end%>
	</ul>
	<nav class="navbar navbar-inverse">
  <div class="container-fluid">
			<div class="navbar-header">
			  <a class="navbar-brand" href="http://localhost:3000">Home</a>
			  <a class="navbar-brand" href="http://localhost:3000/showings">Showings</a>
			  <a class="navbar-brand" href="http://localhost:3000/movies">Movies</a>
			  <a class="navbar-brand" href="http://localhost:3000/theatres">Theatres</a>
			</div>
			</ul>
		  </div>
		</nav>
	<p>Oisin Coburn Github: https://github.com/oisco/movieApp</p>
</div>
<% flash.each do |key, value| %>
  <%= content_tag(:p, value, :class => "flash #{key}") %>
<% end %>

<%= yield %>

</body>
</html>